slice_name: Customers
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 1__table
  extra_form_data: {}
  header_font_size: 0.4
  metric:
    aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: customer_id
      description: This is a unique identifier for a customer
      expression: null
      filterable: true
      groupby: true
      id: 1
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(customer_id)
    optionName: metric_oq9mcrntva_oqfqrl8z4g
    sqlExpression: null
  subheader_font_size: 0.15
  time_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: c8544534-2be5-4c1f-9f1a-55ab8c831645
version: 1.0.0
dataset_uuid: 205d9ead-7ff9-4d3f-99ea-fb5d42c0718c
