slice_name: Orders
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  datasource: 2__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  granularity_sqla: order_date
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      certification_details: null
      certified_by: null
      column_name: order_id
      description: This is a unique identifier for an order
      expression: null
      filterable: true
      groupby: true
      id: 7
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(order_id)
    optionName: metric_mvrpga58ewb_fx1672s1y9f
    sqlExpression: null
  only_total: true
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  time_grain_sqla: P1D
  time_range: No filter
  tooltipTimeFormat: smart_date
  viz_type: echarts_timeseries_bar
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
cache_timeout: null
uuid: 2491bab9-d21b-4530-a437-44e5b131b3be
version: 1.0.0
dataset_uuid: 2dc8068f-f5cd-4741-a161-51b0895e7463
